language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
 
script:
  - xbuild CI.build
  - nunit-console ./src/Pricing.Tests/bin/Debug/Pricing.Tests.dll -exclude Integration,NotWorkingOnMono